import {
  StaffUser,
  ShiftSlot,
  StaffWeeklyAvailability,
  ClockRecord,
  TaskItem,
  ChecklistItem,
  RestaurantDocument,
  OnboardingFormData,
} from './types';

export const INITIAL_STAFF_USERS: StaffUser[] = [
  {
    id: 'staff-mark',
    firstName: 'Mark',
    lastName: 'Zhang',
    email: 'mark.zhang@malayacorner.com.au',
    phone: '0412 889 201',
    role: 'manager',
    staffType: 'bar_staff',
    position: 'General Manager',
    hourlyRate: 36.5,
    onboardingCompleted: true,
    onboardingStatus: 'approved',
    onboardingSubmittedAt: '2025-01-10',
  },
  {
    id: 'staff-john',
    firstName: 'John',
    lastName: 'Tan',
    email: 'john.tan@gmail.com',
    phone: '0423 551 892',
    role: 'staff',
    staffType: 'wait_staff',
    position: 'Wait Staff',
    hourlyRate: 26.5,
    onboardingCompleted: true,
    onboardingStatus: 'approved',
    onboardingSubmittedAt: '2026-02-14',
    tfnProvided: true,
  },
  {
    id: 'staff-lerica',
    firstName: "L'Erica",
    lastName: 'Wong',
    email: 'lerica.wong@outlook.com',
    phone: '0435 912 344',
    role: 'staff',
    staffType: 'wait_staff',
    position: 'Wait Staff',
    hourlyRate: 27.0,
    onboardingCompleted: true,
    onboardingStatus: 'approved',
    onboardingSubmittedAt: '2026-03-01',
  },
  {
    id: 'staff-bowie',
    firstName: 'Bowie',
    lastName: 'Chen',
    email: 'bowie.chen@gmail.com',
    phone: '0450 128 776',
    role: 'staff',
    staffType: 'bar_staff',
    position: 'Bar Staff & Senior Server',
    hourlyRate: 28.0,
    onboardingCompleted: true,
    onboardingStatus: 'approved',
    onboardingSubmittedAt: '2026-01-20',
  },
  {
    id: 'staff-kai',
    firstName: 'Kai',
    lastName: 'Lin',
    email: 'kai.lin@gmail.com',
    phone: '0411 773 229',
    role: 'staff',
    staffType: 'bar_staff',
    position: 'Bar Staff',
    hourlyRate: 26.5,
    onboardingCompleted: true,
    onboardingStatus: 'approved',
    onboardingSubmittedAt: '2026-04-12',
  },
  {
    id: 'staff-maria',
    firstName: 'Maria',
    lastName: 'Santos',
    email: 'maria.santos@gmail.com',
    phone: '0488 239 104',
    role: 'staff',
    staffType: 'wait_staff',
    position: 'Wait Staff',
    hourlyRate: 26.5,
    onboardingCompleted: true,
    onboardingStatus: 'approved',
    onboardingSubmittedAt: '2026-03-18',
  },
  {
    id: 'staff-marcus',
    firstName: 'Marcus',
    lastName: 'Ng',
    email: 'marcus.ng@yahoo.com',
    phone: '0477 441 990',
    role: 'staff',
    staffType: 'wait_staff',
    position: 'Wait Staff',
    hourlyRate: 26.5,
    onboardingCompleted: true,
    onboardingStatus: 'approved',
    onboardingSubmittedAt: '2026-02-28',
  },
  {
    id: 'staff-yannie',
    firstName: 'Yannie',
    lastName: 'Khoo',
    email: 'yannie.khoo@gmail.com',
    phone: '0466 332 118',
    role: 'staff',
    staffType: 'wait_staff',
    position: 'Wait Staff',
    hourlyRate: 26.5,
    onboardingCompleted: true,
    onboardingStatus: 'approved',
    onboardingSubmittedAt: '2026-05-02',
  },
  {
    id: 'staff-manuel',
    firstName: 'Manuel',
    lastName: 'Reyes',
    email: 'manuel.reyes@gmail.com',
    phone: '0499 112 556',
    role: 'staff',
    staffType: 'wait_staff',
    position: 'Kitchen Hand / Runner',
    hourlyRate: 27.5,
    onboardingCompleted: true,
    onboardingStatus: 'approved',
    onboardingSubmittedAt: '2026-02-10',
  },
  {
    id: 'staff-erica',
    firstName: 'Erica',
    lastName: 'Chow',
    email: 'erica.chow@gmail.com',
    phone: '0433 892 441',
    role: 'staff',
    staffType: 'wait_staff',
    position: 'Wait Staff',
    hourlyRate: 26.5,
    onboardingCompleted: true,
    onboardingStatus: 'approved',
    onboardingSubmittedAt: '2026-03-15',
  },
  {
    id: 'staff-iu',
    firstName: 'IU',
    lastName: 'Lee',
    email: 'iu.lee@gmail.com',
    phone: '0421 993 112',
    role: 'staff',
    staffType: 'wait_staff',
    position: 'Wait Staff',
    hourlyRate: 26.5,
    onboardingCompleted: true,
    onboardingStatus: 'approved',
    onboardingSubmittedAt: '2026-04-05',
  },
  {
    id: 'staff-chloe',
    firstName: 'Chloe',
    lastName: 'Lin',
    email: 'chloe.lin@malayacorner.com.au',
    phone: '0439 123 456',
    role: 'staff',
    staffType: 'bar_staff',
    position: 'Bar Staff (New Hire)',
    hourlyRate: 26.0,
    onboardingCompleted: false, // NEW HIRE! Gated from other features until onboarding is submitted!
    onboardingStatus: 'not_started',
  },
  {
    id: 'staff-veronica',
    firstName: 'Veronica',
    lastName: 'Tan',
    email: 'veronica.tan@gmail.com',
    phone: '0415 678 901',
    role: 'staff',
    staffType: 'wait_staff',
    position: 'Wait Staff',
    hourlyRate: 26.5,
    onboardingCompleted: true,
    onboardingStatus: 'approved',
    onboardingSubmittedAt: '2026-03-20',
  },
  {
    id: 'staff-yen',
    firstName: 'Yen',
    lastName: 'Vo',
    email: 'yen.vo@gmail.com',
    phone: '0422 345 678',
    role: 'staff',
    staffType: 'wait_staff',
    position: 'Wait Staff',
    hourlyRate: 26.5,
    onboardingCompleted: true,
    onboardingStatus: 'approved',
    onboardingSubmittedAt: '2026-02-18',
  },
  {
    id: 'staff-france',
    firstName: 'France',
    lastName: 'Delacruz',
    email: 'france.delacruz@gmail.com',
    phone: '0438 901 234',
    role: 'staff',
    staffType: 'wait_staff',
    position: 'Wait Staff',
    hourlyRate: 27.0,
    onboardingCompleted: true,
    onboardingStatus: 'approved',
    onboardingSubmittedAt: '2026-01-25',
  },
];

export const INITIAL_AVAILABILITIES: Record<string, StaffWeeklyAvailability> = {
  'staff-john': {
    id: 'avail-john',
    staffId: 'staff-john',
    weekStartDate: '2026-09-07',
    submittedAt: '2026-09-03 14:20',
    availabilities: {
      MON: { lunch: true, dinner: true },
      TUE: { lunch: true, dinner: true },
      WED: { lunch: false, dinner: true },
      THU: { lunch: false, dinner: false },
      FRI: { lunch: true, dinner: false },
      SAT: { lunch: false, dinner: true },
      SUN: { lunch: false, dinner: true },
    },
  },
  'staff-bowie': {
    id: 'avail-bowie',
    staffId: 'staff-bowie',
    weekStartDate: '2026-09-07',
    submittedAt: '2026-09-02 18:45',
    availabilities: {
      MON: { lunch: true, dinner: true },
      TUE: { lunch: true, dinner: true },
      WED: { lunch: false, dinner: false },
      THU: { lunch: true, dinner: true },
      FRI: { lunch: false, dinner: false },
      SAT: { lunch: false, dinner: false },
      SUN: { lunch: true, dinner: false },
    },
  },
  'staff-kai': {
    id: 'avail-kai',
    staffId: 'staff-kai',
    weekStartDate: '2026-09-07',
    submittedAt: '2026-09-03 10:15',
    availabilities: {
      MON: { lunch: false, dinner: false },
      TUE: { lunch: false, dinner: false },
      WED: { lunch: true, dinner: true },
      THU: { lunch: true, dinner: true },
      FRI: { lunch: false, dinner: false },
      SAT: { lunch: true, dinner: true },
      SUN: { lunch: true, dinner: true },
    },
  },
  'staff-lerica': {
    id: 'avail-lerica',
    staffId: 'staff-lerica',
    weekStartDate: '2026-09-07',
    submittedAt: '2026-09-01 19:30',
    availabilities: {
      MON: { lunch: true, dinner: true },
      TUE: { lunch: false, dinner: false },
      WED: { lunch: true, dinner: true },
      THU: { lunch: false, dinner: false },
      FRI: { lunch: false, dinner: false },
      SAT: { lunch: true, dinner: true },
      SUN: { lunch: true, dinner: false },
    },
  },
  'staff-maria': {
    id: 'avail-maria',
    staffId: 'staff-maria',
    weekStartDate: '2026-09-07',
    submittedAt: '2026-09-02 11:00',
    availabilities: {
      MON: { lunch: false, dinner: false },
      TUE: { lunch: false, dinner: true },
      WED: { lunch: false, dinner: false },
      THU: { lunch: true, dinner: true },
      FRI: { lunch: false, dinner: false },
      SAT: { lunch: false, dinner: false },
      SUN: { lunch: false, dinner: false },
    },
  },
};

// Realistic shifts structured exactly like the CSV attached in File 1
export const INITIAL_SHIFTS: ShiftSlot[] = [
  // Monday
  { id: 's-mon-l1', day: 'MON', dateStr: '2026-09-07', shiftType: 'lunch', startTime: '11:15', endTime: '15:00', assignedStaffId: 'staff-john', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-mon-l2', day: 'MON', dateStr: '2026-09-07', shiftType: 'lunch', startTime: '11:30', endTime: '15:00', assignedStaffId: 'staff-lerica', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-mon-l3', day: 'MON', dateStr: '2026-09-07', shiftType: 'lunch', startTime: '11:15', endTime: '15:00', assignedStaffId: 'staff-bowie', roleRequired: 'Senior Server', status: 'published' },
  { id: 's-mon-d1', day: 'MON', dateStr: '2026-09-07', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-john', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-mon-d2', day: 'MON', dateStr: '2026-09-07', shiftType: 'dinner', startTime: '16:45', endTime: '21:00', assignedStaffId: 'staff-lerica', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-mon-d3', day: 'MON', dateStr: '2026-09-07', shiftType: 'dinner', startTime: '17:15', endTime: '21:30', assignedStaffId: 'staff-bowie', roleRequired: 'Senior Server', status: 'published' },
  { id: 's-mon-d4', day: 'MON', dateStr: '2026-09-07', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-marcus', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-mon-d5', day: 'MON', dateStr: '2026-09-07', shiftType: 'dinner', startTime: '18:00', endTime: '22:00', assignedStaffId: 'staff-mark', roleRequired: 'Manager', status: 'published' },

  // Tuesday
  { id: 's-tue-l1', day: 'TUE', dateStr: '2026-09-08', shiftType: 'lunch', startTime: '11:15', endTime: '15:00', assignedStaffId: 'staff-john', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-tue-l2', day: 'TUE', dateStr: '2026-09-08', shiftType: 'lunch', startTime: '11:15', endTime: '15:00', assignedStaffId: 'staff-bowie', roleRequired: 'Senior Server', status: 'published' },
  { id: 's-tue-d1', day: 'TUE', dateStr: '2026-09-08', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-john', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-tue-d2', day: 'TUE', dateStr: '2026-09-08', shiftType: 'dinner', startTime: '18:00', endTime: '21:30', assignedStaffId: 'staff-maria', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-tue-d3', day: 'TUE', dateStr: '2026-09-08', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-bowie', roleRequired: 'Senior Server', status: 'published' },
  { id: 's-tue-d4', day: 'TUE', dateStr: '2026-09-08', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-marcus', roleRequired: 'Wait Staff', status: 'published' },

  // Wednesday
  { id: 's-wed-l1', day: 'WED', dateStr: '2026-09-09', shiftType: 'lunch', startTime: '11:15', endTime: '15:00', assignedStaffId: 'staff-lerica', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-wed-l2', day: 'WED', dateStr: '2026-09-09', shiftType: 'lunch', startTime: '11:15', endTime: '15:00', assignedStaffId: 'staff-kai', roleRequired: 'Floor Staff', status: 'published' },
  { id: 's-wed-d1', day: 'WED', dateStr: '2026-09-09', shiftType: 'dinner', startTime: '18:00', endTime: '22:00', assignedStaffId: 'staff-john', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-wed-d2', day: 'WED', dateStr: '2026-09-09', shiftType: 'dinner', startTime: '16:45', endTime: '21:00', assignedStaffId: 'staff-lerica', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-wed-d3', day: 'WED', dateStr: '2026-09-09', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-kai', roleRequired: 'Floor Staff', status: 'published' },
  { id: 's-wed-d4', day: 'WED', dateStr: '2026-09-09', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-yannie', roleRequired: 'Wait Staff', status: 'published' },

  // Thursday
  { id: 's-thu-l1', day: 'THU', dateStr: '2026-09-10', shiftType: 'lunch', startTime: '11:15', endTime: '15:00', assignedStaffId: 'staff-kai', roleRequired: 'Floor Staff', status: 'published' },
  { id: 's-thu-l2', day: 'THU', dateStr: '2026-09-10', shiftType: 'lunch', startTime: '11:15', endTime: '15:00', assignedStaffId: 'staff-maria', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-thu-l3', day: 'THU', dateStr: '2026-09-10', shiftType: 'lunch', startTime: '11:15', endTime: '15:00', assignedStaffId: 'staff-bowie', roleRequired: 'Senior Server', status: 'published' },
  { id: 's-thu-d1', day: 'THU', dateStr: '2026-09-10', shiftType: 'dinner', startTime: '17:15', endTime: '21:30', assignedStaffId: 'staff-iu', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-thu-d2', day: 'THU', dateStr: '2026-09-10', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-kai', roleRequired: 'Floor Staff', status: 'published' },
  { id: 's-thu-d3', day: 'THU', dateStr: '2026-09-10', shiftType: 'dinner', startTime: '16:45', endTime: '21:00', assignedStaffId: 'staff-maria', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-thu-d4', day: 'THU', dateStr: '2026-09-10', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-bowie', roleRequired: 'Senior Server', status: 'published' },

  // Friday
  { id: 's-fri-l1', day: 'FRI', dateStr: '2026-09-11', shiftType: 'lunch', startTime: '11:30', endTime: '15:00', assignedStaffId: 'staff-john', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-fri-l2', day: 'FRI', dateStr: '2026-09-11', shiftType: 'lunch', startTime: '11:15', endTime: '15:00', assignedStaffId: 'staff-marcus', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-fri-d1', day: 'FRI', dateStr: '2026-09-11', shiftType: 'dinner', startTime: '17:15', endTime: '21:30', assignedStaffId: 'staff-erica', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-fri-d2', day: 'FRI', dateStr: '2026-09-11', shiftType: 'dinner', startTime: '18:00', endTime: '22:00', assignedStaffId: 'staff-iu', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-fri-d3', day: 'FRI', dateStr: '2026-09-11', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-marcus', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-fri-d4', day: 'FRI', dateStr: '2026-09-11', shiftType: 'dinner', startTime: '16:45', endTime: '21:00', assignedStaffId: 'staff-mark', roleRequired: 'Manager', status: 'published' },

  // Saturday
  { id: 's-sat-l1', day: 'SAT', dateStr: '2026-09-12', shiftType: 'lunch', startTime: '11:15', endTime: '15:30', assignedStaffId: 'staff-lerica', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-sat-l2', day: 'SAT', dateStr: '2026-09-12', shiftType: 'lunch', startTime: '11:30', endTime: '15:30', assignedStaffId: 'staff-manuel', roleRequired: 'Kitchen Hand / Runner', status: 'published' },
  { id: 's-sat-l3', day: 'SAT', dateStr: '2026-09-12', shiftType: 'lunch', startTime: '11:15', endTime: '15:30', assignedStaffId: 'staff-erica', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-sat-l4', day: 'SAT', dateStr: '2026-09-12', shiftType: 'lunch', startTime: '11:15', endTime: '15:30', assignedStaffId: 'staff-kai', roleRequired: 'Floor Staff', status: 'published' },
  { id: 's-sat-l5', day: 'SAT', dateStr: '2026-09-12', shiftType: 'lunch', startTime: '11:15', endTime: '15:30', assignedStaffId: 'staff-yannie', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-sat-l6', day: 'SAT', dateStr: '2026-09-12', shiftType: 'lunch', startTime: '11:15', endTime: '15:30', assignedStaffId: 'staff-marcus', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-sat-d1', day: 'SAT', dateStr: '2026-09-12', shiftType: 'dinner', startTime: '16:45', endTime: '21:00', assignedStaffId: 'staff-john', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-sat-d2', day: 'SAT', dateStr: '2026-09-12', shiftType: 'dinner', startTime: '17:15', endTime: '21:30', assignedStaffId: 'staff-lerica', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-sat-d3', day: 'SAT', dateStr: '2026-09-12', shiftType: 'dinner', startTime: '18:00', endTime: '22:00', assignedStaffId: 'staff-manuel', roleRequired: 'Kitchen Hand / Runner', status: 'published' },
  { id: 's-sat-d4', day: 'SAT', dateStr: '2026-09-12', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-erica', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-sat-d5', day: 'SAT', dateStr: '2026-09-12', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-kai', roleRequired: 'Floor Staff', status: 'published' },
  { id: 's-sat-d6', day: 'SAT', dateStr: '2026-09-12', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-yannie', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-sat-d7', day: 'SAT', dateStr: '2026-09-12', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-marcus', roleRequired: 'Wait Staff', status: 'published' },

  // Sunday
  { id: 's-sun-l1', day: 'SUN', dateStr: '2026-09-13', shiftType: 'lunch', startTime: '11:15', endTime: '15:30', assignedStaffId: 'staff-lerica', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-sun-l2', day: 'SUN', dateStr: '2026-09-13', shiftType: 'lunch', startTime: '11:15', endTime: '15:30', assignedStaffId: 'staff-manuel', roleRequired: 'Kitchen Hand / Runner', status: 'published' },
  { id: 's-sun-l3', day: 'SUN', dateStr: '2026-09-13', shiftType: 'lunch', startTime: '11:15', endTime: '15:30', assignedStaffId: 'staff-kai', roleRequired: 'Floor Staff', status: 'published' },
  { id: 's-sun-l4', day: 'SUN', dateStr: '2026-09-13', shiftType: 'lunch', startTime: '11:15', endTime: '15:30', assignedStaffId: 'staff-bowie', roleRequired: 'Senior Server', status: 'published' },
  { id: 's-sun-l5', day: 'SUN', dateStr: '2026-09-13', shiftType: 'lunch', startTime: '12:00', endTime: '16:00', assignedStaffId: 'staff-mark', roleRequired: 'Manager', status: 'published' },
  { id: 's-sun-d1', day: 'SUN', dateStr: '2026-09-13', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-john', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-sun-d2', day: 'SUN', dateStr: '2026-09-13', shiftType: 'dinner', startTime: '18:00', endTime: '22:00', assignedStaffId: 'staff-manuel', roleRequired: 'Kitchen Hand / Runner', status: 'published' },
  { id: 's-sun-d3', day: 'SUN', dateStr: '2026-09-13', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-erica', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-sun-d4', day: 'SUN', dateStr: '2026-09-13', shiftType: 'dinner', startTime: '16:45', endTime: '21:00', assignedStaffId: 'staff-iu', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-sun-d5', day: 'SUN', dateStr: '2026-09-13', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-kai', roleRequired: 'Floor Staff', status: 'published' },
  { id: 's-sun-d6', day: 'SUN', dateStr: '2026-09-13', shiftType: 'dinner', startTime: '16:45', endTime: '21:30', assignedStaffId: 'staff-yannie', roleRequired: 'Wait Staff', status: 'published' },
  { id: 's-sun-d7', day: 'SUN', dateStr: '2026-09-13', shiftType: 'dinner', startTime: '18:00', endTime: '22:00', assignedStaffId: 'staff-mark', roleRequired: 'Manager', status: 'published' },
];

export const INITIAL_CLOCK_RECORDS: ClockRecord[] = [
  {
    id: 'clk-1',
    staffId: 'staff-john',
    staffName: 'John Tan',
    position: 'Wait Staff',
    date: '2026-09-04',
    shiftType: 'lunch',
    clockInTime: '11:15',
    clockOutTime: '15:00',
    breakMinutes: 0,
    totalHours: 3.75,
    status: 'approved',
    hourlyRate: 26.5,
    notes: 'On time, floor was packed',
  },
  {
    id: 'clk-2',
    staffId: 'staff-bowie',
    staffName: 'Bowie Chen',
    position: 'Senior Server',
    date: '2026-09-04',
    shiftType: 'lunch',
    clockInTime: '11:15',
    clockOutTime: '15:15',
    breakMinutes: 0,
    totalHours: 4.0,
    status: 'approved',
    hourlyRate: 28.0,
    notes: 'Assisted table 12 special allergy order',
  },
  {
    id: 'clk-3',
    staffId: 'staff-john',
    staffName: 'John Tan',
    position: 'Wait Staff',
    date: '2026-09-04',
    shiftType: 'dinner',
    clockInTime: '16:45',
    breakMinutes: 0,
    status: 'clocked_in', // Currently active!
    hourlyRate: 26.5,
    notes: 'Dinner rush station 2',
  },
  {
    id: 'clk-4',
    staffId: 'staff-marcus',
    staffName: 'Marcus Ng',
    position: 'Wait Staff',
    date: '2026-09-04',
    shiftType: 'dinner',
    clockInTime: '16:45',
    breakMinutes: 0,
    status: 'clocked_in',
    hourlyRate: 26.5,
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'task-1',
    title: 'Restock condiment stations & sauce squeeze bottles',
    description: 'Refill sambal, sweet soy sauce, and chilli oil squeeze bottles before the dinner rush.',
    taskType: 'one_off',
    assignedToStaffId: 'staff-john',
    assignedStaffName: 'John Tan',
    assignedByManager: 'Mark Zhang',
    priority: 'high',
    shift: 'dinner',
    targetRole: 'wait_staff',
    dueDate: '2026-09-08 17:30',
    isCompleted: false,
  },
  {
    id: 'task-2',
    title: 'Cutlery roll-up count & polish',
    description: 'Ensure 120 sets of polished forks, spoons, and chopsticks are prepped in station baskets.',
    taskType: 'one_off',
    assignedToStaffId: 'staff-john',
    assignedStaffName: 'John Tan',
    assignedByManager: 'Mark Zhang',
    priority: 'medium',
    shift: 'dinner',
    targetRole: 'wait_staff',
    dueDate: '2026-09-08 18:00',
    isCompleted: true,
    completedAt: '2026-09-08 17:10',
    completedByStaffName: 'John Tan',
    completedByStaffId: 'staff-john',
    completionNote: 'Completed 140 sets and restocked stations 1-4.',
  },
  {
    id: 'task-3',
    title: 'Weekly beverage fridge stock audit & FIFO rotation',
    description: 'Check stock levels of 100PLUS, Yeo’s soy bean, and Tiger beers. Rotate older stock forward and log any expired inventory.',
    taskType: 'recurring_weekly',
    recurringDays: ['MON', 'THU'],
    assignedToStaffId: 'staff-bowie',
    assignedStaffName: 'Bowie Chen',
    assignedByManager: 'Mark Zhang',
    priority: 'medium',
    shift: 'dinner',
    targetRole: 'bar_staff',
    dueDate: 'Every Mon, Thu by 18:30',
    isCompleted: false,
  },
  {
    id: 'task-5',
    title: 'Deep clean dining room booth partitions & glass screens',
    description: 'Spray and polish glass screen partitions between booths 1 through 12 using streak-free cleaner.',
    taskType: 'one_off',
    assignedToStaffId: undefined,
    assignedStaffName: 'Unassigned (Open Team Task)',
    assignedByManager: 'Mark Zhang',
    priority: 'low',
    shift: 'dinner',
    targetRole: 'wait_staff',
    dueDate: '2026-09-08 21:00',
    isCompleted: false,
  },
  {
    id: 'task-6',
    title: 'Weekly ice machine filter flush & scoop sanitization',
    description: 'Drain water trough, wipe inside surfaces with food-safe disinfectant, and replace ice scoop holder.',
    taskType: 'recurring_weekly',
    recurringDays: ['SUN'],
    assignedToStaffId: 'staff-kai',
    assignedStaffName: 'Kai Lin',
    assignedByManager: 'Mark Zhang',
    priority: 'medium',
    shift: 'lunch',
    targetRole: 'bar_staff',
    dueDate: 'Every Sun by 11:30',
    isCompleted: true,
    completedAt: '2026-09-06 11:20',
    completedByStaffName: 'Kai Lin',
    completedByStaffId: 'staff-kai',
    completionNote: 'Flushed filter lines, sanitized scoops, and verified cycle.',
  },
  {
    id: 'task-7',
    title: 'Bar espresso grinder burr calibration & espresso shot yield check',
    description: 'Dial in espresso grind setting for 1:2 extraction ratio within 27 seconds for Teh Tarik & White Coffee.',
    taskType: 'one_off',
    assignedToStaffId: 'staff-bowie',
    assignedStaffName: 'Bowie Chen',
    assignedByManager: 'Mark Zhang',
    priority: 'high',
    shift: 'lunch',
    targetRole: 'bar_staff',
    dueDate: '2026-09-08 10:45',
    isCompleted: false,
  },
  {
    id: 'task-8',
    title: 'Restock dining room tea stations with Chinese tea sets & thermal pots',
    description: 'Boil thermal water towers and replenish Pu-erh and Jasmine tea leaf canisters.',
    taskType: 'one_off',
    assignedToStaffId: 'staff-john',
    assignedStaffName: 'John Tan',
    assignedByManager: 'Mark Zhang',
    priority: 'medium',
    shift: 'dinner',
    targetRole: 'wait_staff',
    dueDate: '2026-09-08 17:00',
    isCompleted: false,
  },
];

export const INITIAL_CHECKLISTS: ChecklistItem[] = [
  // ==========================================
  // BAR STAFF DAILY CHECKLIST (BAR OPERATIONS)
  // ==========================================
  {
    id: 'chk-bar-op-1',
    roleSet: 'bar_staff',
    category: 'Opening',
    title: 'Turn on commercial espresso machine, calibrate grinder, and warm group heads',
    instructions: 'Purge steam wands, lock warm portafilters in group heads, verify 9 bar pump pressure.',
    isCompleted: true,
    completedBy: 'Bowie Chen',
    completedAt: '10:40',
    requiresPhoto: true,
    maxPhotos: 2,
    photos: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    ],
  },
  {
    id: 'chk-bar-op-2',
    roleSet: 'bar_staff',
    category: 'Opening',
    title: 'Check bar display & underbench milk fridge temperature (Must be ≤ 4.0°C)',
    instructions: 'Log digital probe temperature for fresh full-cream and oat milk storage.',
    isCompleted: true,
    completedBy: 'Bowie Chen',
    completedAt: '10:45',
    requiresTemp: true,
    tempReading: '3.4°C',
    requiresPhoto: true,
    maxPhotos: 1,
    photos: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
    ],
  },
  {
    id: 'chk-bar-op-3',
    roleSet: 'bar_staff',
    category: 'Opening',
    title: 'Check beer tap glycol line chiller temperature (Must be ≤ 2.5°C)',
    instructions: 'Verify glycol tank bath temperature reading to prevent draft beer foaming.',
    isCompleted: true,
    completedBy: 'Bowie Chen',
    completedAt: '10:50',
    requiresTemp: true,
    tempReading: '1.8°C',
  },
  {
    id: 'chk-bar-op-4',
    roleSet: 'bar_staff',
    category: 'Opening',
    title: 'Fill bar ice wells with fresh cube ice & sanitize dedicated ice scoops',
    instructions: 'Ensure scoops are stored inside sanitized stainless holster, never left inside ice bins.',
    isCompleted: true,
    completedBy: 'Kai Lin',
    completedAt: '11:00',
    requiresPhoto: true,
    maxPhotos: 2,
    photos: [
      'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    ],
  },
  {
    id: 'chk-bar-op-5',
    roleSet: 'bar_staff',
    category: 'Opening',
    title: 'Prepare fresh bar garnishes & stock Asian syrups (Pandan, Gula Melaka, Calamansi)',
    instructions: 'Slice lemon wheels, lime wedges, fresh mint, and prepare lemongrass syrup bottles.',
    isCompleted: false,
    requiresPhoto: true,
    maxPhotos: 3,
  },
  {
    id: 'chk-bar-fs-1',
    roleSet: 'bar_staff',
    category: 'Mid-Shift Food Safety',
    title: 'Underbench glasswasher chemical wash & sanitize rinse cycle temp (Wash ≥ 65°C, Rinse ≥ 82°C)',
    instructions: 'Verify detergent draw, rinse aid level, and minimum 82°C thermal sanitization cycle.',
    isCompleted: true,
    completedBy: 'Kai Lin',
    completedAt: '12:45',
    requiresTemp: true,
    tempReading: '83.5°C',
    requiresPhoto: true,
    maxPhotos: 1,
    photos: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
    ],
  },
  {
    id: 'chk-bar-fs-2',
    roleSet: 'bar_staff',
    category: 'Mid-Shift Food Safety',
    title: 'Bar dairy fridge temperature check & milk FIFO replenishment (Must be ≤ 4.0°C)',
    instructions: 'Rotate older milk cartons forward and verify seals.',
    isCompleted: false,
    requiresTemp: true,
    requiresPhoto: true,
    maxPhotos: 2,
  },
  {
    id: 'chk-bar-fs-3',
    roleSet: 'bar_staff',
    category: 'Mid-Shift Food Safety',
    title: 'Sanitize bar speed rails, cocktail shakers, blender jugs & refill sanitizer basin (200 ppm)',
    instructions: 'Use chlorine/quat test strip to confirm 200-400 ppm concentration.',
    isCompleted: false,
  },
  {
    id: 'chk-bar-fs-4',
    roleSet: 'bar_staff',
    category: 'Mid-Shift Food Safety',
    title: 'Inspect & restock polished clean bar glassware (Beer chalices, rocks, Teh Tarik glasses)',
    instructions: 'Check for chips or lip stains, polish with micro-fibre cloth under ambient light.',
    isCompleted: false,
    requiresPhoto: false,
    maxPhotos: 2,
  },
  {
    id: 'chk-bar-cl-1',
    roleSet: 'bar_staff',
    category: 'Closing',
    title: 'Chemical backwash espresso group heads, soak steam wands & purge milk lines',
    instructions: 'Use espresso cleaning powder in blind basket, cycle 5 times, soak wands in hot water.',
    isCompleted: false,
    requiresPhoto: true,
    maxPhotos: 2,
  },
  {
    id: 'chk-bar-cl-2',
    roleSet: 'bar_staff',
    category: 'Closing',
    title: 'Melt down bar ice wells with hot water, spray sanitizer, and prop lids open to dry',
    instructions: 'Melt remaining ice, drain wells, wipe clean with sanitizer to prevent mold.',
    isCompleted: false,
  },
  {
    id: 'chk-bar-cl-3',
    roleSet: 'bar_staff',
    category: 'Closing',
    title: 'Clean draft beer tap nozzles, brush spout interiors & cap with sanitizing covers',
    instructions: 'Submerge spouts in fresh sanitizing wash and seal tight with tap hygiene plugs.',
    isCompleted: false,
    requiresPhoto: true,
    maxPhotos: 2,
  },
  {
    id: 'chk-bar-cl-4',
    roleSet: 'bar_staff',
    category: 'Closing',
    title: 'Polish stainless steel bar top, clean drain troughs, sweep & mop under rubber bar mats',
    instructions: 'Lift rubber floor mats, sweep debris, spray degreaser, and mop dry.',
    isCompleted: false,
    requiresPhoto: true,
    maxPhotos: 2,
  },
  {
    id: 'chk-bar-cl-5',
    roleSet: 'bar_staff',
    category: 'Closing',
    title: 'Empty glass bottle dump bins and lock alcoholic beverage display cabinet',
    instructions: 'Transfer bottles to external recycling bin and lock liquor shutter.',
    isCompleted: false,
  },

  // ==========================================
  // WAIT STAFF DAILY CHECKLIST (FLOOR OPERATIONS)
  // ==========================================
  {
    id: 'chk-wait-op-1',
    roleSet: 'wait_staff',
    category: 'Opening',
    title: 'Turn on POS terminals & check EFTPOS receipt paper rolls',
    instructions: 'Power on terminals 1, 2, and 3. Ensure backup paper rolls are stocked.',
    isCompleted: true,
    completedBy: 'John Tan',
    completedAt: '11:05',
  },
  {
    id: 'chk-wait-op-2',
    roleSet: 'wait_staff',
    category: 'Opening',
    title: 'Unlock front entrance & turn on ambient dining lights & Malaysian jazz playlist',
    instructions: 'Check lighting dimmer level at 70%, start restaurant background music.',
    isCompleted: true,
    completedBy: 'John Tan',
    completedAt: '11:10',
  },
  {
    id: 'chk-wait-op-3',
    roleSet: 'wait_staff',
    category: 'Opening',
    title: 'Prepare dining room water carafes, lemon slices, and ice buckets at server station',
    instructions: 'Fill 12 glass water carafes, slice fresh lemons, place ice tongs in clean tray.',
    isCompleted: true,
    completedBy: "L'Erica Wong",
    completedAt: '11:12',
  },
  {
    id: 'chk-wait-op-4',
    roleSet: 'wait_staff',
    category: 'Opening',
    title: 'Check dining table setups, wipe chairs, set QR code stands and table numbers',
    instructions: 'Align tables 1 through 24, check laminated menus and digital ordering QR codes.',
    isCompleted: true,
    completedBy: "L'Erica Wong",
    completedAt: '11:14',
    requiresPhoto: true,
    maxPhotos: 3,
    photos: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80',
    ],
  },
  {
    id: 'chk-wait-op-5',
    roleSet: 'wait_staff',
    category: 'Opening',
    title: 'Restock condiment stations: sambal, sweet soy sauce, and chilli oil squeeze bottles',
    instructions: 'Wipe bottle necks, ensure all 24 table condiment caddies are full.',
    isCompleted: false,
    requiresPhoto: false,
    maxPhotos: 2,
  },
  {
    id: 'chk-wait-fs-1',
    roleSet: 'wait_staff',
    category: 'Mid-Shift Food Safety',
    title: 'Walk-in cold room temperature check (Must be ≤ 4.0°C)',
    instructions: 'Check thermometer on wall of meat and fresh prep walk-in room.',
    isCompleted: true,
    completedBy: 'John Tan',
    completedAt: '12:30',
    requiresTemp: true,
    tempReading: '3.2°C',
    requiresPhoto: true,
    maxPhotos: 1,
    photos: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
    ],
  },
  {
    id: 'chk-wait-fs-2',
    roleSet: 'wait_staff',
    category: 'Mid-Shift Food Safety',
    title: 'Front dining display fridge temperature check (Must be ≤ 4.0°C)',
    instructions: 'Record digital temp display for dessert and beverage showcase.',
    isCompleted: true,
    completedBy: 'John Tan',
    completedAt: '12:32',
    requiresTemp: true,
    tempReading: '3.8°C',
  },
  {
    id: 'chk-wait-fs-3',
    roleSet: 'wait_staff',
    category: 'Mid-Shift Food Safety',
    title: 'Bain-marie hot holding broth temperature check (Must be ≥ 60.0°C for Curry Laksa broth)',
    instructions: 'Insert calibrated needle probe into center of soup reservoir; record reading.',
    isCompleted: false,
    requiresTemp: true,
    requiresPhoto: true,
    maxPhotos: 2,
  },
  {
    id: 'chk-wait-fs-4',
    roleSet: 'wait_staff',
    category: 'Mid-Shift Food Safety',
    title: 'Dining room sanitizer bucket test strip check (200-400 ppm quat)',
    instructions: 'Dip test strip for 10 seconds, match color to 200-400 ppm standard.',
    isCompleted: false,
  },
  {
    id: 'chk-wait-fs-5',
    roleSet: 'wait_staff',
    category: 'Mid-Shift Food Safety',
    title: 'Restock 120 sets of polished cutlery rollups (forks, soup spoons, chopsticks)',
    instructions: 'Wrap polished cutlery in linen napkins and restock floor server station baskets.',
    isCompleted: false,
    requiresPhoto: false,
    maxPhotos: 1,
  },
  {
    id: 'chk-wait-cl-1',
    roleSet: 'wait_staff',
    category: 'Closing',
    title: 'Run end-of-day Z-Report on POS terminals & balance cash drawer float ($200)',
    instructions: 'Print Z-reading, seal credit card batch slip, count notes/coins to $200 float.',
    isCompleted: false,
    requiresPhoto: true,
    maxPhotos: 1,
  },
  {
    id: 'chk-wait-cl-2',
    roleSet: 'wait_staff',
    category: 'Closing',
    title: 'Wipe and sanitize all dining tables, chairs, booth cushions, and high chairs',
    instructions: 'Use sanitizing spray and microfiber cloths on tables 1-24 and booth benches.',
    isCompleted: false,
    requiresPhoto: true,
    maxPhotos: 3,
  },
  {
    id: 'chk-wait-cl-3',
    roleSet: 'wait_staff',
    category: 'Closing',
    title: 'Sweep dining room floor and mop with hospital-grade floor disinfectant',
    instructions: 'Move chairs onto tables, sweep dust/crumbs, mop with fresh hot sanitizer water.',
    isCompleted: false,
    requiresPhoto: true,
    maxPhotos: 2,
  },
  {
    id: 'chk-wait-cl-4',
    roleSet: 'wait_staff',
    category: 'Closing',
    title: 'Empty all dining trash & recycling bins, wash lids, replace heavy-duty liners',
    instructions: 'Tie trash bags securely, dispose into outdoor council dumpsters, reline bins.',
    isCompleted: false,
  },
  {
    id: 'chk-wait-cl-5',
    roleSet: 'wait_staff',
    category: 'Closing',
    title: 'Lock front entrance & rear staff exit, shut down AC units, and arm alarm system',
    instructions: 'Turn key locks, switch off dining air conditioning, set security alarm code.',
    isCompleted: false,
  },
];

export const INITIAL_DOCUMENTS: RestaurantDocument[] = [
  {
    id: 'doc-food-handler-checklist',
    title: 'Food handler skills and knowledge checklist',
    category: 'Food Safety & Hygiene',
    fileName: 'Food handler skills and knowledge checklist.pdf',
    fileSize: '920 KB',
    uploadedBy: 'Manager (Mark Zhang)',
    uploadedFor: 'all',
    uploadedAt: '2026-01-10',
    description: 'Official bilingual (English & Chinese) Food handler skills and knowledge checklist for Standard 3.2.2A compliance.',
    fileUrl: '/Food handler skills and knowledge checklist.pdf',
    isProtected: true,
  },
  {
    id: 'doc-1',
    title: 'Malaya Corner Staff Handbook & Workplace Code 2026',
    category: 'Policy & Handbook',
    fileName: 'Malaya_Corner_Staff_Handbook_2026.pdf',
    fileSize: '2.4 MB',
    uploadedBy: 'Manager (Mark Zhang)',
    uploadedFor: 'all',
    uploadedAt: '2026-01-05',
    description: 'Core operational policies, code of conduct, presentation standards, and leave procedures.',
    isProtected: true,
  },
  {
    id: 'doc-2',
    title: 'Food Safety Program & Allergen Management Matrix',
    category: 'Food Safety & Hygiene',
    fileName: 'Food_Safety_Allergen_Matrix_Qld.pdf',
    fileSize: '1.8 MB',
    uploadedBy: 'Manager (Mark Zhang)',
    uploadedFor: 'all',
    uploadedAt: '2026-01-12',
    description: 'Mandatory standard operating procedures for Brisbane City Council Food Safety Star compliance.',
    isProtected: true,
  },
  {
    id: 'doc-3',
    title: 'Table Service Etiquette & Upselling Guide (Wait Staff)',
    category: 'Training',
    fileName: 'Wait_Staff_Service_Manual.pdf',
    fileSize: '3.1 MB',
    uploadedBy: 'Manager (Mark Zhang)',
    uploadedFor: 'all',
    uploadedAt: '2026-02-01',
    description: 'Sequence of service from greeting, drink recommendations, laksa pairings to payment processing.',
  },
  {
    id: 'doc-sub-john-1',
    title: 'John Tan - Photo ID & Work Clearance Document',
    category: 'Staff Submission',
    fileName: 'John_Tan_ID_Clearance_2026.pdf',
    fileSize: '412 KB',
    uploadedBy: 'John Tan',
    uploadedFor: 'staff-john',
    uploadedAt: '2026-02-14',
    description: 'Submitted during staff onboarding. Photo ID and employee verification.',
  },
  {
    id: 'doc-sub-john-2',
    title: 'John Tan - Signed Food Handler Skills & Knowledge Checklist',
    category: 'Staff Submission',
    fileName: 'John_Tan_Food_Handler_Checklist.pdf',
    fileSize: '580 KB',
    uploadedBy: 'John Tan',
    uploadedFor: 'staff-john',
    uploadedAt: '2026-02-14',
    description: 'Submitted during staff onboarding. Standard 3.2.2A verification.',
    fileUrl: '/Food handler skills and knowledge checklist.pdf',
  },
  {
    id: 'doc-sub-john-3',
    title: 'John Tan - ATO Tax File Number (TFN) Declaration',
    category: 'Tax & Super',
    fileName: 'John_Tan_TFN_Declaration.pdf',
    fileSize: '650 KB',
    uploadedBy: 'John Tan',
    uploadedFor: 'staff-john',
    uploadedAt: '2026-02-14',
    description: 'Submitted during staff onboarding for payroll processing.',
  },
  {
    id: 'doc-sub-john-4',
    title: 'John Tan - Food Hygiene Online Training Certificate',
    category: 'Staff Submission',
    fileName: 'John_Tan_Food_Hygiene_Certificate.pdf',
    fileSize: '890 KB',
    uploadedBy: 'John Tan',
    uploadedFor: 'staff-john',
    uploadedAt: '2026-02-14',
    description: 'Certified Wait Staff Food Safety qualification under Supervisor Mark Zhang.',
  },
  {
    id: 'doc-sub-bowie-1',
    title: 'Bowie Chen - Food Hygiene Certificate & TFN',
    category: 'Staff Submission',
    fileName: 'Bowie_Chen_Onboarding_Bundle.pdf',
    fileSize: '1.2 MB',
    uploadedBy: 'Bowie Chen',
    uploadedFor: 'staff-bowie',
    uploadedAt: '2026-01-20',
    description: 'Verified by Mark Zhang.',
  },
];

export const INITIAL_ONBOARDING_DATA: Record<string, OnboardingFormData> = {
  'staff-john': {
    q1_email: 'john.tan@gmail.com',
    q2_firstNameMiddle: 'John Sheng',
    q3_lastName: 'Tan',
    q4_dob: '1998-05-14',
    q5_mobile: '0423 551 892',
    q6_emailAddress: 'john.tan@gmail.com',
    q7_superProvider: 'AustralianSuper',
    q8_superMemberNumber: 'AUS-8891024',
    q9_bankName: 'Commonwealth Bank of Australia (CBA)',
    q10_bankBsb: '064-000',
    q11_bankAccountNumber: '10928374',
    q12_vevoDoc: {
      fileName: 'John_Tan_ID_Clearance_2026.pdf',
      fileSize: '412 KB',
      fileType: 'application/pdf',
      uploadedAt: '2026-02-14 09:20',
    },
    q13_foodHandlerDoc: {
      fileName: 'John_Tan_Food_Handler_Checklist.pdf',
      fileSize: '580 KB',
      fileType: 'application/pdf',
      uploadedAt: '2026-02-14 09:25',
    },
    q14_tfnDoc: {
      fileName: 'John_Tan_TFN_Declaration.pdf',
      fileSize: '650 KB',
      fileType: 'application/pdf',
      uploadedAt: '2026-02-14 09:30',
    },
    q15_foodHygieneCert: {
      fileName: 'John_Tan_Food_Hygiene_Certificate.pdf',
      fileSize: '890 KB',
      fileType: 'application/pdf',
      uploadedAt: '2026-02-14 09:35',
    },
  },
};

